name: prism
description: "A new Flutter project for monitoring and health tracking using Firebase."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Utility Packages ---
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  provider: ^6.1.2

  # --- Firebase Core Services ---
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.3
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.4.0

  # --- Authentication ---
  google_sign_in: ^6.2.1

  # --- Bluetooth & IoT ---
  flutter_blue_plus: ^1.32.10

  # --- HTTP & SMS ---
  http: ^1.1.0

  # --- Permissions ---
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- Asset Section ---
  # assets:
  #   - assets/images/
  #   - assets/icons/
  # Add more folders or files if needed

  # --- Fonts (optional example) ---
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
